plugins {
    id 'fabric-loom' version '1.16.1'
    id 'eclipse'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

loom {
    runs {
        client {
            client()
            configName = 'Fabric Client 1.21.1'
            runDir = '../run-fabric-client'
        }

        server {
            server()
            configName = 'Fabric Server 1.21.1'
            runDir = '../run-fabric-server'
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', '../src/main/java']
            exclude 'net/redchujelly/cluttered/config/**'
            exclude 'net/redchujelly/cluttered/datagen/**'
            exclude 'net/redchujelly/cluttered/setup/ClutteredEvents.java'
            exclude 'net/redchujelly/cluttered/setup/ClutteredLootModifiers.java'
        }
        resources.srcDirs = ['src/main/resources', '../src/main/resources', '../src/generated/resources']
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mod_id', project.mod_id
    inputs.property 'mod_name', project.mod_name
    inputs.property 'mod_description', project.mod_description
    inputs.property 'mod_license', project.mod_license
    inputs.property 'loader_version', project.loader_version
    inputs.property 'minecraft_version', project.minecraft_version

    filesMatching('fabric.mod.json') {
        expand(
                version: project.version,
                mod_id: project.mod_id,
                mod_name: project.mod_name,
                mod_description: project.mod_description,
                mod_license: project.mod_license,
                loader_version: project.loader_version,
                minecraft_version: project.minecraft_version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
