plugins {
    id 'fabric-loom' version '1.16.1'
    id 'eclipse'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

loom {
    runs {
        client {
            client()
            configName = 'Fabric Client 1.21.1'
            runDir = '../run-fabric-client'
        }

        server {
            server()
            configName = 'Fabric Server 1.21.1'
            runDir = '../run-fabric-server'
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
            exclude 'net/redchujelly/cluttered/config/**'
            exclude 'net/redchujelly/cluttered/datagen/**'
            exclude 'net/redchujelly/cluttered/setup/ClutteredEvents.java'
            exclude 'net/redchujelly/cluttered/setup/ClutteredLootModifiers.java'
        }
        resources.srcDirs = ['src/main/resources', 'src/generated/resources']
    }
}

def fabricModProperties = [
        version          : version,
        mod_id           : mod_id,
        mod_name         : mod_name,
        mod_description  : mod_description,
        mod_license      : mod_license,
        loader_version   : loader_version,
        minecraft_version: minecraft_version
]

def releaseJarVersion = (project.mod_version as String).replace('-fabric-dev', '') + '[Fabric]'

processResources {
    inputs.properties(fabricModProperties)

    filesMatching('fabric.mod.json') {
        expand(fabricModProperties)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

tasks.named('remapJar').configure {
    archiveBaseName.set('Cluttered')
    archiveVersion.set(releaseJarVersion)
    archiveClassifier.set('')
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
