package net.redchujelly.cluttered.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.redchujelly.cluttered.Cluttered;
import net.redchujelly.cluttered.setup.BlockRegistration;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ClutteredBlockTags extends BlockTagsProvider {
    public ClutteredBlockTags(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, Cluttered.MODID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tagNewWoodset("willow");
        tagNewWoodset("flowering_willow");
        tagNewWoodset("poplar");
        tagNewWoodset("flowering_poplar");
        tagNewWoodset("crabapple");
        tagNewWoodset("flowering_crabapple");
        tagNewWoodset("sycamore");
        tagNewWoodset("fluorescent_maple");
        tagNewWoodset("blue_mushroom");
        tagNewWoodset("red_mushroom");

        tag(BlockTags.MINEABLE_WITH_HOE)
                .add(BlockRegistration.BLUE_MUSHROOM_CAP.get())
                .add(BlockRegistration.RED_MUSHROOM_CAP.get())
                .add(BlockRegistration.EYE_BLOCK.get())
                .add(BlockRegistration.SMALL_BUSH.get());

        tag(BlockTags.ENCHANTMENT_POWER_PROVIDER)
                .add(BlockRegistration.WILLOW_BOOKSHELF_BLACK_CAT.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_CALICO_CAT.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_COBWEB.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_BOTTLES.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_VASE.get())
                .add(BlockRegistration.PUMPKIN_BOOKSHELF.get())

                .add(BlockRegistration.ANTIQUE_BOOK_STAND.get())
                .add(BlockRegistration.ANCIENT_CODEX.get())
                .add(BlockRegistration.BUNNY_BOOK_ENDS.get())
                .add(BlockRegistration.ANTIQUE_LIBRARY_BOOKS.get())
                .add(BlockRegistration.COTTAGE_BOOKCASE.get())
                .add(BlockRegistration.BAMBOO_BOOKSHELF.get())
                .add(BlockRegistration.FWISH_BOOKCASE.get())
                .add(BlockRegistration.RETRO_CAFE_SHELF.get())
                .add(BlockRegistration.BOOK_OPEN.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS_PASTEL.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS_SHELVED.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS_PASTEL_SHELVED.get())
                .add(BlockRegistration.BOOK_OPEN.get())
                .add(BlockRegistration.STACK_OF_BOOKS.get())
                .add(BlockRegistration.STACK_OF_BOOKS_TALL.get())
                .add(BlockRegistration.DARKWOOD_DECORATIVE_SHELVES_SOUTHERN_FLAIR.get())
                .add(BlockRegistration.DARKWOOD_DECORATIVE_SHELVES_GEOMETRIC.get())
                .add(BlockRegistration.DARKWOOD_DECORATIVE_SHELVES_QUILTED.get())
                .add(BlockRegistration.DARKWOOD_ENDTABLE.get())
                .add(BlockRegistration.LUNAR_OBSERVATORY_BOOKS.get())
                .add(BlockRegistration.RITO_BOOKS.get())
                .add(BlockRegistration.SMALL_BOOKCASE.get())
                .add(BlockRegistration.WOODEN_BLOCK_BOOKSHELF_PASTEL.get())

        ;

        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(BlockRegistration.BLUE_MUSHROOM_CAP.get())
                .add(BlockRegistration.RED_MUSHROOM_CAP.get())
                .add(BlockRegistration.WILLOW_DOOR.get())
                .add(BlockRegistration.WILLOW_LOG_DOOR.get())
                .add(BlockRegistration.WILLOW_GARDEN_DOOR.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_BLACK_CAT.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_BOTTLES.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_COBWEB.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_VASE.get())
                .add(BlockRegistration.WILLOW_BOOKSHELF_CALICO_CAT.get())

                .add(BlockRegistration.YELLOW_PLANTER.get())
                .add(BlockRegistration.PINK_PLANTER.get())
                .add(BlockRegistration.PURPLE_PLANTER.get())
                .add(BlockRegistration.BEIGE_PLANTER.get())
                .add(BlockRegistration.GREEN_PLANTER.get())
                .add(BlockRegistration.FLUORESCENT_PLANTER.get())
                .add(BlockRegistration.RED_PLANTER.get())
                .add(BlockRegistration.BLUE_PLANTER.get())
                .add(BlockRegistration.STARRY_WALLPAPER.get())
                .add(BlockRegistration.STARRY_WALLPAPER_TOP.get())
                .add(BlockRegistration.STARRY_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.DARK_STARRY_WALLPAPER.get())
                .add(BlockRegistration.DARK_STARRY_WALLPAPER_TOP.get())
                .add(BlockRegistration.DARK_STARRY_WALLPAPER_BOTTOM.get())

                .add(BlockRegistration.RETRO_RAINBOW_WALLPAPER.get())
                .add(BlockRegistration.APPLE_WALLPAPER.get())
                .add(BlockRegistration.BLUE_ROSE_STRIPED_WALLPAPER.get())
                .add(BlockRegistration.BLUE_ROSE_STRIPED_WALLPAPER_TOP.get())
                .add(BlockRegistration.BLUE_ROSE_STRIPED_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.CHECKERED_FRUIT_WALLPAPER.get())
                .add(BlockRegistration.CHECKERED_PINK_WALLPAPER.get())
                .add(BlockRegistration.CHECKERED_PINK_STRAWBERRY_WALLPAPER.get())
                .add(BlockRegistration.CHECKERED_GREEN_WALLPAPER.get())
                .add(BlockRegistration.CHECKERED_GREEN_STRAWBERRY_WALLPAPER.get())

                .add(BlockRegistration.CHIC_WALLPAPER.get())
                .add(BlockRegistration.CHIC_WALLPAPER_LOWER_TRIM.get())
                .add(BlockRegistration.CHIC_WALLPAPER_UPPER_TRIM.get())
                .add(BlockRegistration.FLORAL_BERRY_WALLPAPER.get())
                .add(BlockRegistration.FLORAL_BERRY_WALLPAPER_TOP.get())
                .add(BlockRegistration.FLORAL_BERRY_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.FLORAL_BORDER_WALLPAPER.get())
                .add(BlockRegistration.CONFECTIONARY_WALLPAPER.get())
                .add(BlockRegistration.CONFECTIONARY_WALLPAPER_TOP.get())
                .add(BlockRegistration.CONFECTIONARY_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.GHOST_WALLPAPER.get())
                .add(BlockRegistration.GHOST_WALLPAPER_TRIM.get())
                .add(BlockRegistration.GHOST_WALLPAPER_TOP.get())
                .add(BlockRegistration.GHOST_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.GHOST_WALLPAPER_WAINSCOTING.get())

                .add(BlockRegistration.HALLOWEEN_WALLPAPER.get())
                .add(BlockRegistration.TARTAN_YELLOW_WALLPAPER.get())
                .add(BlockRegistration.FISH_WALLPAPER.get())
                .add(BlockRegistration.TROPICAL_FISH_WALLPAPER.get())
                .add(BlockRegistration.HALLOWEEN_WALLPAPER_TOP.get())
                .add(BlockRegistration.HALLOWEEN_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.HALLOWEEN_WAINSCOTING.get())
                .add(BlockRegistration.MARIGOLD_WALLPAPER.get())
                .add(BlockRegistration.MARIGOLD_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.MARIGOLD_WALLPAPER_TOP.get())
                .add(BlockRegistration.MINT_WALLPAPER.get())
                .add(BlockRegistration.MINT_WALLPAPER_TOP.get())
                .add(BlockRegistration.MINT_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.PINK_STRIPE_WALLPAPER_LOWER_TRIM.get())
                .add(BlockRegistration.PINK_STRIPE_WALLPAPER.get())
                .add(BlockRegistration.PINK_STRIPE_WALLPAPER_UPPER_TRIM.get())
                .add(BlockRegistration.RIALTO_GOLD_WALLPAPER.get())
                .add(BlockRegistration.RIALTO_GOLD_WALLPAPER_TOP.get())
                .add(BlockRegistration.RIALTO_GOLD_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.STRIPED_FLORAL_WALLPAPER.get())
                .add(BlockRegistration.STRIPED_FLORAL_WALLPAPER_BOTTOM.get())
                .add(BlockRegistration.STRIPED_FLORAL_WALLPAPER_TOP.get())

                .add(BlockRegistration.DIAMOND_WALLPAPER_APPLE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLACKBERRY.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLUEBERRY.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BONES.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BOUQUET.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BROWN_MUSHROOM.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_GREEN_GRAPES.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_LEMON.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ORANGE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PEAR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PLUM.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_RED_MUSHROOM.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PURPLE_GRAPES.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_STRAWBERRY.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ANCHOR.get())

                .add(BlockRegistration.DIAMOND_WALLPAPER_APPLE_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLACKBERRY_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLUEBERRY_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BONES_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BOUQUET_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BROWN_MUSHROOM_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_GREEN_GRAPES_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_LEMON_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ORANGE_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PEAR_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PLUM_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_RED_MUSHROOM_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PURPLE_GRAPES_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_STRAWBERRY_TOP_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ANCHOR_TOP_BROWN.get())

                .add(BlockRegistration.DIAMOND_WALLPAPER_APPLE_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLACKBERRY_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLUEBERRY_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BONES_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BOUQUET_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BROWN_MUSHROOM_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_GREEN_GRAPES_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_LEMON_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ORANGE_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PEAR_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PLUM_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_RED_MUSHROOM_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PURPLE_GRAPES_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_STRAWBERRY_BOTTOM_BROWN.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ANCHOR_BOTTOM_BROWN.get())

                .add(BlockRegistration.DIAMOND_WALLPAPER_APPLE_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLACKBERRY_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLUEBERRY_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BOUQUET_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_GREEN_GRAPES_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_LEMON_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ORANGE_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PEAR_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PLUM_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_RED_MUSHROOM_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PURPLE_GRAPES_TOP_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_STRAWBERRY_TOP_COLOR.get())

                .add(BlockRegistration.DIAMOND_WALLPAPER_APPLE_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLACKBERRY_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLUEBERRY_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BOUQUET_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_GREEN_GRAPES_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_LEMON_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ORANGE_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PEAR_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PLUM_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_RED_MUSHROOM_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PURPLE_GRAPES_BOTTOM_COLOR.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_STRAWBERRY_BOTTOM_COLOR.get())

                .add(BlockRegistration.DIAMOND_WALLPAPER_APPLE_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLACKBERRY_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLUEBERRY_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BONES_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BOUQUET_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_GREEN_GRAPES_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_LEMON_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ORANGE_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PEAR_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PLUM_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_RED_MUSHROOM_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PURPLE_GRAPES_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_STRAWBERRY_TOP_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ANCHOR_TOP_WHITE.get())

                .add(BlockRegistration.DIAMOND_WALLPAPER_APPLE_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLACKBERRY_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BLUEBERRY_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BONES_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_BOUQUET_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_GREEN_GRAPES_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_LEMON_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ORANGE_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PEAR_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PLUM_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_RED_MUSHROOM_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_PURPLE_GRAPES_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_STRAWBERRY_BOTTOM_WHITE.get())
                .add(BlockRegistration.DIAMOND_WALLPAPER_ANCHOR_BOTTOM_WHITE.get())

                .add(BlockRegistration.WICKER_BLOCK.get())
                .add(BlockRegistration.PUMPKIN_BOOKSHELF.get())
                .add(BlockRegistration.DYNASTY_DOOR.get())
                .add(BlockRegistration.WOOD_WINDOW_DIVIDED.get())
                .add(BlockRegistration.WOOD_WINDOW_PANE.get())
                .add(BlockRegistration.WOOD_SCREEN_DOOR.get())
                .add(BlockRegistration.WOOD_FRENCH_DOOR.get())

                .add(BlockRegistration.BLUE_WAINSCOTING.get())
                .add(BlockRegistration.BROWN_WAINSCOTING.get())

                .add(BlockRegistration.WOODEN_PICKET_FENCE.get())
                .add(BlockRegistration.WOODEN_PICKET_FENCE_GATE.get())
                .add(BlockRegistration.WOODEN_BRACKET_BOW.get())
                .add(BlockRegistration.WOODEN_BRACKET_SCROLL.get())
                .add(BlockRegistration.WOODEN_BRACKET_BOW_SCROLL.get())
                .add(BlockRegistration.WOODEN_BRACKET_STAR.get())
                .add(BlockRegistration.WOODEN_BRACKET_STAR_SCROLL.get())
                .add(BlockRegistration.WOODEN_BRACKET_SCROLL_SHELF.get())
                .add(BlockRegistration.WOODEN_BRACKET_VICTORIAN.get())
                .add(BlockRegistration.ART_NOUVEAU_DOOR_DARK.get())
                .add(BlockRegistration.ART_NOUVEAU_DOOR.get())

                .add(BlockRegistration.APPLE_CHAIR.get())
                .add(BlockRegistration.BIRDHOUSE_UNPAINTED.get())
                .add(BlockRegistration.BIRDHOUSE_BLUE.get())
                .add(BlockRegistration.BIRDHOUSE_PASTEL.get())
                .add(BlockRegistration.BIRDHOUSE_RED.get())
                .add(BlockRegistration.BRIEFCASE_BLANK.get())
                .add(BlockRegistration.BRIEFCASE_ROVER.get())
                .add(BlockRegistration.BUNNY_BOOK_ENDS.get())
                .add(BlockRegistration.BOX_OF_PAINTS.get())
                .add(BlockRegistration.BUTTON_STOOL.get())
                .add(BlockRegistration.CARDBOARD_BOX.get())
                .add(BlockRegistration.COFFEE_GRINDER.get())
                .add(BlockRegistration.ANTIQUE_MINI_TABLE.get())
                .add(BlockRegistration.ANTIQUE_MINI_TABLE.get())
                .add(BlockRegistration.ANCIENT_CODEX.get())
                .add(BlockRegistration.ANTIQUE_BOOK_STAND.get())
                .add(BlockRegistration.ANTIQUE_LIBRARY_BOOKS.get())
                .add(BlockRegistration.BEE_LAMP.get())
                .add(BlockRegistration.BEE_LAMP_ANGRY.get())
                .add(BlockRegistration.RECORD_PLAYER_BLUE.get())
                .add(BlockRegistration.RECORD_PLAYER_BROWN.get())
                .add(BlockRegistration.RECORD_PLAYER_YELLOW.get())
                .add(BlockRegistration.RECORD_PLAYER_RED.get())
                .add(BlockRegistration.RECORD_PLAYER_PURPLE.get())
                .add(BlockRegistration.RECORD_PLAYER_PINK.get())
                .add(BlockRegistration.RECORD_PLAYER_WHITE.get())
                .add(BlockRegistration.COTTAGE_SIDE_TABLE.get())
                .add(BlockRegistration.COTTAGE_CHAIR.get())
                .add(BlockRegistration.COTTAGE_CHAIR_CUSHIONED.get())
                .add(BlockRegistration.COTTAGE_OTTOMAN.get())
                .add(BlockRegistration.NEWSPAPER_PILE_TALL.get())
                .add(BlockRegistration.NEWSPAPER_PILE_SHORT.get())
                .add(BlockRegistration.PAPER_PILE.get())
                .add(BlockRegistration.FENCE_SHELF.get())
                .add(BlockRegistration.PEDESTAL_HK.get())
                .add(BlockRegistration.PICNIC_BASKET.get())
                .add(BlockRegistration.PICNIC_BASKET_PREPARED.get())
                .add(BlockRegistration.BASKET_OF_PRODUCE.get())
                .add(BlockRegistration.BASKET_OF_FLOWERS.get())
                .add(BlockRegistration.COTTAGE_BOOKCASE.get())
                .add(BlockRegistration.COTTAGE_STANDING_LAMP.get())
                .add(BlockRegistration.DRYING_HERBS.get())
                .add(BlockRegistration.HANGING_CLOTH.get())
                .add(BlockRegistration.BAMBOO_BOOKSHELF.get())
                .add(BlockRegistration.FWISH_BOOKCASE.get())
                .add(BlockRegistration.RETRO_CAFE_SHELF.get())
                .add(BlockRegistration.RETRO_CAFE_SHELF_WINDOW.get())
                .add(BlockRegistration.POTION_SHELF.get())
                .add(BlockRegistration.CHINA_CABINET.get())
                .add(BlockRegistration.ENDTABLE_AMETHYST.get())
                .add(BlockRegistration.ENDTABLE_BUBBLEGUM.get())
                .add(BlockRegistration.ENDTABLE_CHARCOAL.get())
                .add(BlockRegistration.ENDTABLE_MEADOW.get())
                .add(BlockRegistration.ENDTABLE_PERIWINKLE.get())
                .add(BlockRegistration.ENDTABLE_SUNSHINE.get())
                .add(BlockRegistration.ENDTABLE_WOOD.get())

                .add(BlockRegistration.ENDTABLE_DECOR.get())
                .add(BlockRegistration.NIGHTSTAND_GREEN.get())
                .add(BlockRegistration.DESK_BROWN.get())
                .add(BlockRegistration.DESK_GREEN.get())
                .add(BlockRegistration.DESK_BROWN_CLUTTERED.get())
                .add(BlockRegistration.DESK_GREEN_CLUTTERED.get())
                .add(BlockRegistration.ROVER_STOOL.get())
                .add(BlockRegistration.MADONNA_OTTOMAN.get())
                .add(BlockRegistration.RUBIKS_CUBE.get())
                .add(BlockRegistration.RUBIKS_CUBE_PASTEL.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS_PASTEL.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS.get())
                .add(BlockRegistration.SMALL_SHELF.get())
                .add(BlockRegistration.SMALL_SHELF_PINK.get())
                .add(BlockRegistration.TRADITIONAL_RADIO.get())
                .add(BlockRegistration.SEWING_MANNEQUIN.get())
                .add(BlockRegistration.ANTIQUE_STANDING_LAMP.get())
                .add(BlockRegistration.BULLETIN_BOARD.get())
                .add(BlockRegistration.BULLETIN_BOARD_CLUTTERED.get())
                .add(BlockRegistration.LOVELY_LOVE_SEAT.get())
                .add(BlockRegistration.LOVELY_LOVE_SEAT_BLACK.get())
                .add(BlockRegistration.ARMCHAIR_WHITE.get())
                .add(BlockRegistration.ARMCHAIR_LIGHT_GRAY.get())
                .add(BlockRegistration.ARMCHAIR_GRAY.get())
                .add(BlockRegistration.ARMCHAIR_BLACK.get())
                .add(BlockRegistration.ARMCHAIR_BROWN.get())
                .add(BlockRegistration.ARMCHAIR_RED.get())
                .add(BlockRegistration.ARMCHAIR_ORANGE.get())
                .add(BlockRegistration.ARMCHAIR_YELLOW.get())
                .add(BlockRegistration.ARMCHAIR_LIME.get())
                .add(BlockRegistration.ARMCHAIR_GREEN.get())
                .add(BlockRegistration.ARMCHAIR_CYAN.get())
                .add(BlockRegistration.ARMCHAIR_LIGHT_BLUE.get())
                .add(BlockRegistration.ARMCHAIR_BLUE.get())
                .add(BlockRegistration.ARMCHAIR_PURPLE.get())
                .add(BlockRegistration.ARMCHAIR_MAGENTA.get())
                .add(BlockRegistration.ARMCHAIR_PINK.get())
                .add(BlockRegistration.ARMCHAIR_FUCHSIA.get())
                .add(BlockRegistration.ARMCHAIR_IVORY.get())
                .add(BlockRegistration.ARMCHAIR_FLOWER.get())
                .add(BlockRegistration.ARMCHAIR_STRAWBERRY.get())
                .add(BlockRegistration.ARMCHAIR_HEART.get())
                .add(BlockRegistration.ARMCHAIR_WATERMELON.get())
                .add(BlockRegistration.ARMCHAIR_LEMON.get())
                .add(BlockRegistration.ARMCHAIR_STARRY.get())
                .add(BlockRegistration.ARMCHAIR_BLACK_CAT.get())
                .add(BlockRegistration.COTTAGE_ARMCHAIR.get())
                .add(BlockRegistration.DARKWOOD_CHAIR_SOUTHERN_FLAIR.get())
                .add(BlockRegistration.DARKWOOD_CHAIR_GEOMETRIC.get())
                .add(BlockRegistration.DARKWOOD_CHAIR_QUILTED.get())
                .add(BlockRegistration.DARKWOOD_SOFA_GEOMETRIC.get())
                .add(BlockRegistration.DARKWOOD_SOFA_QUILTED.get())
                .add(BlockRegistration.DARKWOOD_SOFA_SOUTHERN_FLAIR.get())
                .add(BlockRegistration.DARKWOOD_DECORATIVE_SHELVES_GEOMETRIC.get())
                .add(BlockRegistration.DARKWOOD_DECORATIVE_SHELVES_QUILTED.get())
                .add(BlockRegistration.DARKWOOD_DECORATIVE_SHELVES_SOUTHERN_FLAIR.get())
                .add(BlockRegistration.DARKWOOD_TABLE.get())
                .add(BlockRegistration.DARKWOOD_ENDTABLE.get())
                .add(BlockRegistration.DARKWOOD_STOOL.get())
                .add(BlockRegistration.DARKWOOD_CABINET.get())
                .add(BlockRegistration.DARKWOOD_CLOCK.get())
                .add(BlockRegistration.DARKWOOD_BED_GEOMETRIC.get())
                .add(BlockRegistration.DARKWOOD_BED_QUILTED.get())
                .add(BlockRegistration.DARKWOOD_BED_SOUTHERN_FLAIR.get())
                .add(BlockRegistration.TABLE_PLAIN.get())
                .add(BlockRegistration.TABLE_TABLECLOTH.get())
                .add(BlockRegistration.DORADO_CABINET.get())
                .add(BlockRegistration.DORADO_CABINET_CLUTTERED.get())
                .add(BlockRegistration.HAVANA_CABINET.get())
                .add(BlockRegistration.HAVANA_CABINET_CLUTTERED.get())
                .add(BlockRegistration.MUREX_CABINET.get())
                .add(BlockRegistration.MUREX_CABINET_CLUTTERED.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS_PASTEL_SHELVED.get())
                .add(BlockRegistration.ROW_OF_SMALL_BOOKS_SHELVED.get())
                .add(BlockRegistration.MUREX_CABINET_CLUTTERED.get())
                .add(BlockRegistration.TEDDY_BEAR.get())

                .add(BlockRegistration.KITCHEN_SET_BROWN_COUNTER.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_COUNTER_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_COUNTER_OUTER_CORNER_RIGHT.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_COUNTER_OUTER_CORNER_LEFT.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_COUNTER_SINK.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_CABINET.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_CABINET_MINI.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_CABINET_GLASS.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_CABINET_OPEN.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_CABINET_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_BROWN_CABINET_OUTER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_COUNTER.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_COUNTER_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_COUNTER_OUTER_CORNER_RIGHT.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_COUNTER_OUTER_CORNER_LEFT.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_COUNTER_SINK.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_CABINET.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_CABINET_MINI.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_CABINET_GLASS.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_CABINET_OPEN.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_CABINET_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_LIGHT_GREEN_CABINET_OUTER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_COUNTER.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_COUNTER_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_COUNTER_OUTER_CORNER_RIGHT.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_COUNTER_OUTER_CORNER_LEFT.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_COUNTER_SINK.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_CABINET.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_CABINET_MINI.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_CABINET_GLASS.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_CABINET_OPEN.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_CABINET_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_PINK_CABINET_OUTER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_COUNTER.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_COUNTER_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_COUNTER_OUTER_CORNER_RIGHT.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_COUNTER_OUTER_CORNER_LEFT.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_COUNTER_SINK.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_CABINET.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_CABINET_MINI.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_CABINET_GLASS.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_CABINET_OPEN.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_CABINET_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_PURPLE_CABINET_OUTER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_COUNTER.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_COUNTER_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_COUNTER_OUTER_CORNER_RIGHT.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_COUNTER_OUTER_CORNER_LEFT.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_COUNTER_SINK.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_CABINET.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_CABINET_MINI.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_CABINET_GLASS.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_CABINET_OPEN.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_CABINET_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_WHITE_CABINET_OUTER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_COUNTER.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_COUNTER_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_COUNTER_OUTER_CORNER_RIGHT.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_COUNTER_OUTER_CORNER_LEFT.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_COUNTER_SINK.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_CABINET.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_CABINET_MINI.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_CABINET_GLASS.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_CABINET_OPEN.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_CABINET_INNER_CORNER.get())
                .add(BlockRegistration.KITCHEN_SET_YELLOW_CABINET_OUTER_CORNER.get())

                .add(BlockRegistration.BLACK_CAT_COUNTER_DRAWERS.get())
                .add(BlockRegistration.BLACK_CAT_COUNTER_LEFT_DOOR.get())
                .add(BlockRegistration.BLACK_CAT_COUNTER_RIGHT_DOOR.get())
                .add(BlockRegistration.BLACK_CAT_SINK.get())
                .add(BlockRegistration.BLACK_CAT_TABLE.get())
                .add(BlockRegistration.SWEETHEART_COUNTER_DRAWERS.get())
                .add(BlockRegistration.SWEETHEART_COUNTER_LEFT_DOOR.get())
                .add(BlockRegistration.SWEETHEART_COUNTER_RIGHT_DOOR.get())
                .add(BlockRegistration.SWEETHEART_SINK.get())
                .add(BlockRegistration.SWEETHEART_TABLE.get())
                .add(BlockRegistration.SWEETHEART_BAKING_SET_INGREDIENTS.get())
                .add(BlockRegistration.SWEETHEART_BAKING_SET_BOWL.get())
                .add(BlockRegistration.CONFECTIONERY_TABLE_BLUE.get())
                .add(BlockRegistration.CONFECTIONERY_TABLE_PINK.get())
                .add(BlockRegistration.BOOK_OPEN.get())
                .add(BlockRegistration.CARD_INDEX.get())
                .add(BlockRegistration.ENVELOPE_STACK.get())
                .add(BlockRegistration.FLOWER_DESK_LAMP.get())

                .add(BlockRegistration.FLOWER_SHELF_BLUE.get())
                .add(BlockRegistration.FLOWER_SHELF_GREEN.get())
                .add(BlockRegistration.FLOWER_SHELF_PASTEL_YELLOW.get())
                .add(BlockRegistration.FLOWER_SHELF_PINK.get())
                .add(BlockRegistration.FLOWER_SHELF_PURPLE.get())
                .add(BlockRegistration.FLOWER_SHELF_YELLOW.get())
                .add(BlockRegistration.FWISH_ARMCHAIR.get())
                .add(BlockRegistration.FWISH_OTTOMAN.get())
                .add(BlockRegistration.GENERAL_STORE_CABINET.get())
                .add(BlockRegistration.HEAVENLY_ORNAMENTAL_ARRAY.get())
                .add(BlockRegistration.PLANT_LADDER.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_BLUE.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_GREEN.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_RED.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_YELLOW.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_PASTEL_BLUE.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_PASTEL_YELLOW.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_PASTEL_PINK.get())
                .add(BlockRegistration.PUZZLE_PIECE_TABLE_PASTEL_PURPLE.get())
                .add(BlockRegistration.SKETCHBOOK_SINGLE.get())
                .add(BlockRegistration.STACK_OF_BOOKS.get())
                .add(BlockRegistration.STACK_OF_BOOKS_TALL.get())
                .add(BlockRegistration.STEAMPUNK_GLOBE.get())
                .add(BlockRegistration.WINE_BOTTLE_RACK.get())
                .add(BlockRegistration.YELLOW_NOTEPAD.get())
                .add(BlockRegistration.SLICED_BREAD.get())
                .add(BlockRegistration.ROSE_END_TABLE.get())
                .add(BlockRegistration.ROSE_END_TABLE_BLACK.get())
                .add(BlockRegistration.VIAL_STAND.get())
                .add(BlockRegistration.PINEAPPLE.get())
                .add(BlockRegistration.HONEYCOMB_LAMP.get())
                .add(BlockRegistration.UNLIVING_CHAIR.get())
                .add(BlockRegistration.VIOLET_SCREEN.get())
                .add(BlockRegistration.HANGING_SHELVES_PLANTS.get())
                .add(BlockRegistration.HANGING_SHELVES_POTTERY.get())
                .add(BlockRegistration.SMALL_BUSH.get())

                .add(BlockRegistration.RED_MUSHROOM_TV.get())
                .add(BlockRegistration.RED_MUSHROOM_WARDROBE.get())
                .add(BlockRegistration.RED_MUSHROOM_TABLE.get())
                .add(BlockRegistration.RED_MUSHROOM_BED.get())
                .add(BlockRegistration.RED_MUSHROOM_LAMP.get())
                .add(BlockRegistration.BLUE_MUSHROOM_TV.get())
                .add(BlockRegistration.BLUE_MUSHROOM_WARDROBE.get())
                .add(BlockRegistration.BLUE_MUSHROOM_TABLE.get())
                .add(BlockRegistration.BLUE_MUSHROOM_BED.get())
                .add(BlockRegistration.BLUE_MUSHROOM_LAMP.get())

                .add(BlockRegistration.SEWING_TABLE.get())
                .add(BlockRegistration.IMPERIAL_TABLE.get())
                .add(BlockRegistration.LUNAR_OBSERVATORY_TABLE.get())
                .add(BlockRegistration.IMPERIAL_CHAIR.get())
                .add(BlockRegistration.SEWING_CLUTTER.get())
                .add(BlockRegistration.LUNAR_OBSERVATORY_PAPER_BASKET.get())
                .add(BlockRegistration.LUNAR_OBSERVATORY_BOOKS.get())
                .add(BlockRegistration.LUNAR_OBSERVATORY_PEDESTAL.get())
                .add(BlockRegistration.FILING_BOX.get())

                .add(BlockRegistration.PASTEL_CABINET.get())
                .add(BlockRegistration.PASTEL_CHAIR.get())
                .add(BlockRegistration.PASTEL_STOOL.get())
                .add(BlockRegistration.PASTEL_LIGHT.get())
                .add(BlockRegistration.PASTEL_BED.get())
                .add(BlockRegistration.PASTEL_TABLE.get())
                .add(BlockRegistration.PASTEL_WARDROBE.get())
                .add(BlockRegistration.PASTEL_PLUSH.get())

                .add(BlockRegistration.MERMAID_DRESSER.get())

                .add(BlockRegistration.MINI_HANGING_TERRARIUMS.get())
                .add(BlockRegistration.OFFICE_SUPPLIES_A.get())
                .add(BlockRegistration.OFFICE_SUPPLIES_B.get())
                .add(BlockRegistration.RITO_BOOKS.get())
                .add(BlockRegistration.WEDDING_ARCH.get())
                .add(BlockRegistration.SMALL_BOOKCASE.get())
                .add(BlockRegistration.WOODEN_BLOCK_BOOKSHELF_PASTEL.get())
                ;
        tag(BlockTags.BEDS)
                .add(BlockRegistration.BLUE_MUSHROOM_BED.get())
                .add(BlockRegistration.RED_MUSHROOM_BED.get())
                .add(BlockRegistration.DARKWOOD_BED_GEOMETRIC.get())
                .add(BlockRegistration.DARKWOOD_BED_QUILTED.get())
                .add(BlockRegistration.DARKWOOD_BED_SOUTHERN_FLAIR.get())
                .add(BlockRegistration.PASTEL_BED.get())
        ;

        tag(BlockTags.WOODEN_DOORS)
                .add(BlockRegistration.WILLOW_LOG_DOOR.get())
                .add(BlockRegistration.WILLOW_GARDEN_DOOR.get())
                .add(BlockRegistration.DYNASTY_DOOR.get())
                .add(BlockRegistration.WOOD_FRENCH_DOOR.get())
                .add(BlockRegistration.WOOD_SCREEN_DOOR.get())
                .add(BlockRegistration.ART_NOUVEAU_DOOR_DARK.get())
                .add(BlockRegistration.ART_NOUVEAU_DOOR.get());

        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(BlockRegistration.CHALCEDONY.get())
                .add(BlockRegistration.CHALCEDONY_STAIRS.get())
                .add(BlockRegistration.CHALCEDONY_SLAB.get())
                .add(BlockRegistration.POLISHED_CHALCEDONY.get())
                .add(BlockRegistration.CHALCEDONY_BRICKS.get())
                .add(BlockRegistration.CHALCEDONY_BRICK_STAIRS.get())
                .add(BlockRegistration.CHALCEDONY_BRICK_SLAB.get())
                .add(BlockRegistration.CHALCEDONY_TILES.get())
                .add(BlockRegistration.CHALCEDONY_SMALL_TILES.get())
                .add(BlockRegistration.CHISELED_CHALCEDONY.get())
                .add(BlockRegistration.CHALCEDONY_BORDER.get())
                .add(BlockRegistration.CHALCEDONY_ACANTHUS.get())
                .add(BlockRegistration.CHALCEDONY_HELIX.get())
                .add(BlockRegistration.CHALCEDONY_MEANDER.get())
                .add(BlockRegistration.STARRY_CHISELED_CHALCEDONY.get())
                .add(BlockRegistration.CHALCEDONY_PILLAR.get())
                .add(BlockRegistration.CHALCEDONY_PILLAR_BASE.get())
                .add(BlockRegistration.CHALCEDONY_PILLAR_DORIC.get())
                .add(BlockRegistration.CHALCEDONY_PILLAR_IONIC.get())
                .add(BlockRegistration.STARRY_CHALCEDONY_PILLAR.get())
                .add(BlockRegistration.STARRY_CHALCEDONY_PILLAR_BASE.get())
                .add(BlockRegistration.STARRY_CHALCEDONY_PILLAR_DORIC.get())
                .add(BlockRegistration.STARRY_CHALCEDONY_PILLAR_IONIC.get())
                .add(BlockRegistration.CHALCEDONY_WINDOW.get())
                .add(BlockRegistration.CHALCEDONY_WINDOW_PANE.get())

                .add(BlockRegistration.CHALCEDONY_BALUSTRADE.get())
                .add(BlockRegistration.CHALCEDONY_PICKET_FENCE.get())
                .add(BlockRegistration.CHALCEDONY_PICKET_FENCE_GATE.get())

                .add(BlockRegistration.CHALCEDONY_BRACKET_BOW.get())
                .add(BlockRegistration.CHALCEDONY_BRACKET_SCROLL.get())
                .add(BlockRegistration.CHALCEDONY_BRACKET_BOW_SCROLL.get())
                .add(BlockRegistration.CHALCEDONY_BRACKET_STAR.get())
                .add(BlockRegistration.CHALCEDONY_BRACKET_STAR_SCROLL.get())
                .add(BlockRegistration.CHALCEDONY_BRACKET_SCROLL_SHELF.get())
                .add(BlockRegistration.CHALCEDONY_BRACKET_VICTORIAN.get())

                .add(BlockRegistration.DEEP_CHALCEDONY.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_STAIRS.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_SLAB.get())
                .add(BlockRegistration.DEEP_POLISHED_CHALCEDONY.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRICKS.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRICK_STAIRS.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRICK_SLAB.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_TILES.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_SMALL_TILES.get())
                .add(BlockRegistration.DEEP_CHISELED_CHALCEDONY.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BORDER.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_ACANTHUS.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_HELIX.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_MEANDER.get())
                .add(BlockRegistration.DEEP_STARRY_CHISELED_CHALCEDONY.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PILLAR.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PILLAR_BASE.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PILLAR_DORIC.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PILLAR_IONIC.get())
                .add(BlockRegistration.DEEP_STARRY_CHALCEDONY_PILLAR.get())
                .add(BlockRegistration.DEEP_STARRY_CHALCEDONY_PILLAR_BASE.get())
                .add(BlockRegistration.DEEP_STARRY_CHALCEDONY_PILLAR_IONIC.get())
                .add(BlockRegistration.DEEP_STARRY_CHALCEDONY_PILLAR_DORIC.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_WINDOW.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_WINDOW_PANE.get())

                .add(BlockRegistration.DEEP_CHALCEDONY_BRACKET_BOW.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRACKET_SCROLL.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRACKET_BOW_SCROLL.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRACKET_STAR.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRACKET_STAR_SCROLL.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRACKET_SCROLL_SHELF.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BRACKET_VICTORIAN.get())

                .add(BlockRegistration.DEEP_CHALCEDONY_BALUSTRADE.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PICKET_FENCE.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PICKET_FENCE_GATE.get())

                .add(BlockRegistration.MARBLE.get())
                .add(BlockRegistration.MARBLE_STAIRS.get())
                .add(BlockRegistration.MARBLE_SLAB.get())
                .add(BlockRegistration.POLISHED_MARBLE.get())
                .add(BlockRegistration.MARBLE_BRICKS.get())
                .add(BlockRegistration.MARBLE_BRICK_STAIRS.get())
                .add(BlockRegistration.MARBLE_BRICK_SLAB.get())
                .add(BlockRegistration.MARBLE_TILES.get())
                .add(BlockRegistration.MARBLE_SMALL_TILES.get())
                .add(BlockRegistration.CHISELED_MARBLE.get())
                .add(BlockRegistration.MARBLE_BORDER.get())
                .add(BlockRegistration.MARBLE_ACANTHUS.get())
                .add(BlockRegistration.MARBLE_HELIX.get())
                .add(BlockRegistration.MARBLE_MEANDER.get())
                .add(BlockRegistration.STARRY_CHISELED_MARBLE.get())
                .add(BlockRegistration.MARBLE_PILLAR.get())
                .add(BlockRegistration.MARBLE_PILLAR_BASE.get())
                .add(BlockRegistration.MARBLE_PILLAR_DORIC.get())
                .add(BlockRegistration.MARBLE_PILLAR_IONIC.get())

                .add(BlockRegistration.MARBLE_BRACKET_BOW.get())
                .add(BlockRegistration.MARBLE_BRACKET_SCROLL.get())
                .add(BlockRegistration.MARBLE_BRACKET_BOW_SCROLL.get())
                .add(BlockRegistration.MARBLE_BRACKET_STAR.get())
                .add(BlockRegistration.MARBLE_BRACKET_STAR_SCROLL.get())
                .add(BlockRegistration.MARBLE_BRACKET_SCROLL_SHELF.get())
                .add(BlockRegistration.MARBLE_BRACKET_VICTORIAN.get())

                .add(BlockRegistration.MARBLE_BALUSTRADE.get())
                .add(BlockRegistration.MARBLE_PICKET_FENCE.get())
                .add(BlockRegistration.MARBLE_PICKET_FENCE_GATE.get())
                .add(BlockRegistration.HONEY_JAR_BLOCK.get())
                .add(BlockRegistration.STRAWBERRY_JAR_BLOCK.get())
                .add(BlockRegistration.APRICOT_JAR_BLOCK.get())
                .add(BlockRegistration.CHERRY_JAR_BLOCK.get())
                .add(BlockRegistration.ORANGE_JAR_BLOCK.get())
                .add(BlockRegistration.BLUEBERRY_JAR_BLOCK.get())
                .add(BlockRegistration.BLACK_CAT_WINDOW.get())
                .add(BlockRegistration.BLACK_CAT_WINDOW_PANE.get())

                .add(BlockRegistration.GINGERBREAD_BRICKS.get())
                .add(BlockRegistration.GINGERBREAD_BRICK_STAIRS.get())
                .add(BlockRegistration.GINGERBREAD_BRICK_SLAB.get())
                .add(BlockRegistration.GINGERBREAD_BRICKS_SIDE.get())
                .add(BlockRegistration.GINGERBREAD_BRICKS_TOP.get())
                .add(BlockRegistration.GINGERBREAD_BRICKS_TOP_CORNER.get())

                .add(BlockRegistration.ESPERANCA_TILE.get())
                .add(BlockRegistration.HANNISH_TILE.get())
                .add(BlockRegistration.LILIY_HILLS_TILE.get())
                .add(BlockRegistration.AURA_TILES.get())
                .add(BlockRegistration.BIFURCATING_TILES.get())
                .add(BlockRegistration.BLACK_AMARYLLIS_TILES.get())
                .add(BlockRegistration.ROSETTE_TILES.get())
                .add(BlockRegistration.SEISMIC_TILES.get())

                .add(BlockRegistration.MARBLE_TEXTILES.get())
                .add(BlockRegistration.CHALCEDONY_TEXTILES.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_TEXTILES.get())
                .add(BlockRegistration.STONE_TEXTILES.get())
                .add(BlockRegistration.X_TILE_TERRACOTTA.get())
                .add(BlockRegistration.X_TILE_INVERSE_TERRACOTTA.get())
                .add(BlockRegistration.X_TILE_BLUE.get())
                .add(BlockRegistration.X_TILE_INVERSE_BLUE.get())
                .add(BlockRegistration.X_TILE_GRAY.get())
                .add(BlockRegistration.X_TILE_INVERSE_GRAY.get())

                .add(BlockRegistration.GREENHOUSE_WINDOW.get())
                .add(BlockRegistration.GREENHOUSE_WINDOW_CIRCLE.get())
                .add(BlockRegistration.GREENHOUSE_WINDOW_ROUNDED.get())
                .add(BlockRegistration.GREENHOUSE_WINDOW_RADIAL_LEFT.get())
                .add(BlockRegistration.GREENHOUSE_WINDOW_RADIAL_RIGHT.get())
                .add(BlockRegistration.GREENHOUSE_WINDOW_ARCH_LEFT.get())
                .add(BlockRegistration.GREENHOUSE_WINDOW_ARCH_RIGHT.get())
                .add(BlockRegistration.GREENHOUSE_WINDOW_POINT.get())

                .add(BlockRegistration.VERDANT_TILE.get())
                .add(BlockRegistration.VERDANT_TILE_EDGE.get())
                .add(BlockRegistration.VERDANT_TILE_CORNER.get())

                .add(BlockRegistration.IRIDESCENT_TILES.get())
                .add(BlockRegistration.SMALL_IRIDESCENT_TILES.get())
                .add(BlockRegistration.GREEN_TILES.get())
                .add(BlockRegistration.SMALL_GREEN_TILES.get())
                .add(BlockRegistration.YELLOW_TILES.get())
                .add(BlockRegistration.SMALL_YELLOW_TILES.get())
                .add(BlockRegistration.PINK_TILES.get())
                .add(BlockRegistration.SMALL_PINK_TILES.get())
                .add(BlockRegistration.PURPLE_TILES.get())
                .add(BlockRegistration.SMALL_PURPLE_TILES.get())
                .add(BlockRegistration.KITCHEN_TILES.get())

                .add(BlockRegistration.MARBLE_TILE.get())
                .add(BlockRegistration.MARBLE_TILE_CHISELED.get())
                .add(BlockRegistration.MARBLE_TILE_BORDER.get())
                .add(BlockRegistration.MARBLE_TILE_BORDER_DETAIL.get())
                .add(BlockRegistration.MARBLE_TILE_BORDER_CIRCLE.get())
                .add(BlockRegistration.MARBLE_TILE_CORNER.get())
                .add(BlockRegistration.MARBLE_TILE_CORNER_CIRCLE.get())

                .add(BlockRegistration.ALABASTER_WINDOW_DIVIDED.get())
                .add(BlockRegistration.ALABASTER_WINDOW_PANE.get())
                .add(BlockRegistration.ALABASTER_SCREEN_DOOR.get())
                .add(BlockRegistration.ALABASTER_FRENCH_DOOR.get())
                .add(BlockRegistration.ALABASTER_WAINSCOTING.get())

                .add(BlockRegistration.COLOSSEO_PILLAR_BASE.get())
                .add(BlockRegistration.COLOSSEO_PILLAR.get())
                .add(BlockRegistration.COLOSSEO_PILLAR_TOP.get())
                .add(BlockRegistration.CHISELED_GOLD_BLOCK.get())
                .add(BlockRegistration.VARYING_BRICKS.get())
                .add(BlockRegistration.VARYING_BRICKS_BORDER.get())

                .add(BlockRegistration.CUPID_BENCH.get())
                .add(BlockRegistration.CAT_MUGS_CLUTTERED.get())
                .add(BlockRegistration.CAT_PLANT_POT_BLACK.get())
                .add(BlockRegistration.CAT_PLANT_POT_ORANGE.get())
                .add(BlockRegistration.KITCHEN_SCALE.get())
                .add(BlockRegistration.BIKE_YELLOW.get())
                .add(BlockRegistration.BIKE_YELLOW_FLOWERS.get())
                .add(BlockRegistration.BIKE_BLUE.get())
                .add(BlockRegistration.BIKE_BLUE_FLOWERS.get())
                .add(BlockRegistration.BIKE_PURPLE.get())
                .add(BlockRegistration.BIKE_PURPLE_FLOWERS.get())
                .add(BlockRegistration.BIKE_PINK.get())
                .add(BlockRegistration.BIKE_PINK_FLOWERS.get())
                .add(BlockRegistration.GUMBALL_MACHINE_PURPLE.get())
                .add(BlockRegistration.GUMBALL_MACHINE_RED.get())
                .add(BlockRegistration.GUMBALL_MACHINE_BLUE.get())
                .add(BlockRegistration.MUSHROOM_JARS.get())

                .add(BlockRegistration.MUSHROOM_TERRARIUM_BROWN.get())
                .add(BlockRegistration.MUSHROOM_TERRARIUM_RED.get())
                .add(BlockRegistration.GLOWSHROOM_TERRARIUM_YELLOW.get())
                .add(BlockRegistration.GLOWSHROOM_TERRARIUM_GREEN.get())
                .add(BlockRegistration.GLOWSHROOM_TERRARIUM_BLUE.get())
                .add(BlockRegistration.GLOWSHROOM_TERRARIUM_PURPLE.get())
                .add(BlockRegistration.GLOWSHROOM_TERRARIUM_PINK.get())
                .add(BlockRegistration.HANGING_PLANT_POT_FLOWERS.get())
                .add(BlockRegistration.HANGING_PLANT_POT_GRASS.get())
                .add(BlockRegistration.MINI_CACTUS_SET.get())
                .add(BlockRegistration.CAGED_BULB.get())
                .add(BlockRegistration.COLOSSEO_WALL_LANTERN.get())

                .add(BlockRegistration.OSSON_PENDANT_BLACK.get())
                .add(BlockRegistration.OSSON_PENDANT_BROWN.get())
                .add(BlockRegistration.OSSON_PENDANT_ORANGE.get())
                .add(BlockRegistration.OSSON_PENDANT_RACING_GREEN.get())
                .add(BlockRegistration.OSSON_PENDANT_SAGE_GREEN.get())
                .add(BlockRegistration.OSSON_PENDANT_YELLOW.get())
                .add(BlockRegistration.OSSON_PENDANT_RED.get())
                .add(BlockRegistration.OSSON_PENDANT_WHITE.get())

                .add(BlockRegistration.ANIMATED_FLAG_RAINBOW.get())
                .add(BlockRegistration.ANIMATED_FLAG_LESBIAN.get())
                .add(BlockRegistration.ANIMATED_FLAG_BISEXUAL.get())
                .add(BlockRegistration.ANIMATED_FLAG_PANSEXUAL.get())
                .add(BlockRegistration.ANIMATED_FLAG_ASEXUAL.get())
                .add(BlockRegistration.ANIMATED_FLAG_TRANSGENDER.get())
                .add(BlockRegistration.ANIMATED_FLAG_NONBINARY.get())
                .add(BlockRegistration.STAINED_GLASS_LAMP.get())
                .add(BlockRegistration.TWO_FLOWER_POTS.get())
                .add(BlockRegistration.SEWING_MACHINE_ANTIQUE.get())
                .add(BlockRegistration.WATERING_CAN.get())
                .add(BlockRegistration.WATERING_CAN_COPPER.get())
                .add(BlockRegistration.STARS_PENDANT.get())
                .add(BlockRegistration.MOON_DECORATION.get())
                .add(BlockRegistration.MOON_PENDANT.get())
                .add(BlockRegistration.BRASS_KEY.get())
                .add(BlockRegistration.JAM_JARS.get())
                .add(BlockRegistration.FLOWER_SHELF_PLANT.get())
                .add(BlockRegistration.FLOWER_TEA_KETTLE.get())
                .add(BlockRegistration.POLAROID_CAMERA.get())
                .add(BlockRegistration.RETRO_FRIDGE_BLACK.get())
                .add(BlockRegistration.RETRO_FRIDGE_BLUE.get())
                .add(BlockRegistration.RETRO_FRIDGE_PINK.get())
                .add(BlockRegistration.RETRO_FRIDGE_PURPLE.get())
                .add(BlockRegistration.RETRO_FRIDGE_RED.get())
                .add(BlockRegistration.RETRO_FRIDGE_TURQUOISE.get())
                .add(BlockRegistration.RETRO_FRIDGE_WHITE.get())
                .add(BlockRegistration.RETRO_FRIDGE_YELLOW.get())
                .add(BlockRegistration.RETRO_TOASTER_BLACK.get())
                .add(BlockRegistration.RETRO_TOASTER_BLUE.get())
                .add(BlockRegistration.RETRO_TOASTER_PINK.get())
                .add(BlockRegistration.RETRO_TOASTER_PURPLE.get())
                .add(BlockRegistration.RETRO_TOASTER_RED.get())
                .add(BlockRegistration.RETRO_TOASTER_TURQUOISE.get())
                .add(BlockRegistration.RETRO_TOASTER_WHITE.get())
                .add(BlockRegistration.RETRO_TOASTER_YELLOW.get())
                .add(BlockRegistration.SALT_PEPPER_SHAKERS.get())
                .add(BlockRegistration.WINE_BOTTLES.get())
                .add(BlockRegistration.HOPPIN_PARK_LANTERN.get())
                .add(BlockRegistration.SEA_GEM_LANTERN.get())
                .add(BlockRegistration.SAFE_NOVAKID.get())
                .add(BlockRegistration.POK_TA_POK_HOOP.get())
                .add(BlockRegistration.POK_TA_POK_HOOP_SNAKES.get())
                .add(BlockRegistration.PASTRY_DISPLAY_CASE.get())
                .add(BlockRegistration.GLASS_FLOWER_VASE.get())
                .add(BlockRegistration.LUNAR_OBSERVATORY_GLOBE.get())
                .add(BlockRegistration.MERMAID_PEARL.get())
                .add(BlockRegistration.PAINT_WATER_JAR.get())
                .add(BlockRegistration.LUNAR_OBSERVATORY_JARS.get())
                .add(BlockRegistration.ASSORTED_GLASS_JARS.get())
                .add(BlockRegistration.SMALL_GLASS_JARS.get())
                .add(BlockRegistration.ASSORTED_SPICE_JARS.get())
                .add(BlockRegistration.LEMON_TABLE.get())

                .add(BlockRegistration.ROVER_MUG.get())
                .add(BlockRegistration.SELTZER_CANS.get())

                .add(BlockRegistration.SMALL_CAULDRON.get())
                .add(BlockRegistration.STEAMPUNK_LAMP.get())
                .add(BlockRegistration.TARRY_TOWN_STOVE.get())
                .add(BlockRegistration.SEAWEED_PLANTER.get())
        ;
        tag(BlockTags.CLIMBABLE)
                .add(BlockRegistration.WILLOW_VINES.get());
        tag(BlockTags.WOOL)
                .add(BlockRegistration.THREAD_SPOOL_GREEN.get())
                .add(BlockRegistration.THREAD_SPOOL_YELLOW.get())
                .add(BlockRegistration.THREAD_SPOOL_PINK.get())
                .add(BlockRegistration.THREAD_SPOOL_PURPLE.get())
                .add(BlockRegistration.SAND_SEAL_PLUSH_BLUE.get())
                .add(BlockRegistration.SAND_SEAL_PLUSH_RED.get())
                .add(BlockRegistration.SAND_SEAL_PLUSH_GREEN.get())
                .add(BlockRegistration.FABRIC_BOLTS.get())
                ;

        tag(BlockTags.BIG_DRIPLEAF_PLACEABLE)
                .add(BlockRegistration.YELLOW_PLANTER.get())
                .add(BlockRegistration.PINK_PLANTER.get())
                .add(BlockRegistration.PURPLE_PLANTER.get())
                .add(BlockRegistration.BEIGE_PLANTER.get())
                .add(BlockRegistration.GREEN_PLANTER.get())
                .add(BlockRegistration.FLUORESCENT_PLANTER.get())
                .add(BlockRegistration.RED_PLANTER.get())
                .add(BlockRegistration.BLUE_PLANTER.get());
        tag(BlockTags.SMALL_DRIPLEAF_PLACEABLE)
                .add(BlockRegistration.YELLOW_PLANTER.get())
                .add(BlockRegistration.PINK_PLANTER.get())
                .add(BlockRegistration.PURPLE_PLANTER.get())
                .add(BlockRegistration.BEIGE_PLANTER.get())
                .add(BlockRegistration.GREEN_PLANTER.get())
                .add(BlockRegistration.FLUORESCENT_PLANTER.get())
                .add(BlockRegistration.RED_PLANTER.get())
                .add(BlockRegistration.BLUE_PLANTER.get());
        tag(BlockTags.DEAD_BUSH_MAY_PLACE_ON)
                .add(BlockRegistration.YELLOW_PLANTER.get())
                .add(BlockRegistration.PINK_PLANTER.get())
                .add(BlockRegistration.PURPLE_PLANTER.get())
                .add(BlockRegistration.BEIGE_PLANTER.get())
                .add(BlockRegistration.GREEN_PLANTER.get())
                .add(BlockRegistration.FLUORESCENT_PLANTER.get())
                .add(BlockRegistration.RED_PLANTER.get())
                .add(BlockRegistration.BLUE_PLANTER.get());
        tag(BlockTags.MUSHROOM_GROW_BLOCK)
                .add(BlockRegistration.YELLOW_PLANTER.get())
                .add(BlockRegistration.PINK_PLANTER.get())
                .add(BlockRegistration.PURPLE_PLANTER.get())
                .add(BlockRegistration.BEIGE_PLANTER.get())
                .add(BlockRegistration.GREEN_PLANTER.get())
                .add(BlockRegistration.FLUORESCENT_PLANTER.get())
                .add(BlockRegistration.RED_PLANTER.get())
                .add(BlockRegistration.BLUE_PLANTER.get());
        tag(BlockTags.BAMBOO_PLANTABLE_ON)
                .add(BlockRegistration.YELLOW_PLANTER.get())
                .add(BlockRegistration.PINK_PLANTER.get())
                .add(BlockRegistration.PURPLE_PLANTER.get())
                .add(BlockRegistration.BEIGE_PLANTER.get())
                .add(BlockRegistration.GREEN_PLANTER.get())
                .add(BlockRegistration.FLUORESCENT_PLANTER.get())
                .add(BlockRegistration.RED_PLANTER.get())
                .add(BlockRegistration.BLUE_PLANTER.get());
        tag(BlockTags.SAPLINGS)
                .add(BlockRegistration.WILLOW_SAPLING.get())
                .add(BlockRegistration.POPLAR_SAPLING.get());
        tag(BlockTags.LEAVES)
                .add(BlockRegistration.WILLOW_LEAVES.get())
                .add(BlockRegistration.POPLAR_LEAVES.get());
        tag(BlockTags.WOODEN_FENCES)
                .add(BlockRegistration.WOODEN_PICKET_FENCE.get())
                .add(BlockRegistration.MARBLE_PICKET_FENCE.get())
                .add(BlockRegistration.CHALCEDONY_PICKET_FENCE.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PICKET_FENCE.get())
                .add(BlockRegistration.WEDDING_ARCH.get());
        tag(BlockTags.FENCES)
                .add(BlockRegistration.WEDDING_ARCH.get())
                .add(BlockRegistration.MARBLE_BALUSTRADE.get())
                .add(BlockRegistration.MARBLE_PICKET_FENCE.get())
                .add(BlockRegistration.CHALCEDONY_BALUSTRADE.get())
                .add(BlockRegistration.CHALCEDONY_PICKET_FENCE.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_BALUSTRADE.get())
                .add(BlockRegistration.DEEP_CHALCEDONY_PICKET_FENCE.get())
                .add(BlockRegistration.WOODEN_PICKET_FENCE.get());
        tag(BlockTags.LEAVES)
                .add(BlockRegistration.MAPLE_LEAVES_FLOWERING.get());
        tag(BlockTags.MINEABLE_WITH_HOE)
                .add(BlockRegistration.MAPLE_LEAVES_FLOWERING.get());
    }

    public void tagNewWoodset(String woodType){

        Block log = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_log"));
        Block wood = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_wood"));
        Block strippedLog = null;
        Block strippedWood = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, "stripped_" + woodType + "_log"))) {
            strippedLog = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, "stripped_" + woodType + "_log"));
            strippedWood = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, "stripped_" + woodType + "_wood"));
        }
        Block planks = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_planks"));
        Block stairs = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_stairs"));
        Block slab = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_slab"));
        Block fence = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_fence"));
        Block fenceGate = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_fence_gate"));
        Block button = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_button"));
        Block pressurePlate = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_pressure_plate"));
        Block floorSign = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_sign"));
        Block wallSign = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_wall_sign"));
        Block hangingSign = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_hanging_sign"));
        Block hangingWallSign = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_wall_hanging_sign"));
        Block door = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_door"))) {
            door = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_door"));
        }
        Block trapdoor = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_trapdoor"))) {
            trapdoor = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_trapdoor"));
        }
        Block window = null;
        Block pane = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_window"))) {
            window = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_window"));
            pane = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_window_pane"));
        }
        Block bookshelf = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_bookshelf"))) {
            bookshelf = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_bookshelf"));
        }
        Block wainscoting = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_wainscoting"))) {
            wainscoting = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_wainscoting"));
        }
        Block leaves = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_leaves"))) {
            leaves = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_leaves"));
        }
        Block sapling = null;
        if (BuiltInRegistries.BLOCK.containsKey(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_sapling"))) {
            sapling = BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath(Cluttered.MODID, woodType + "_sapling"));
        }

        tag(BlockTags.LOGS)
                .add(log)
                .add(wood);
        tag(BlockTags.LOGS_THAT_BURN)
                .add(log)
                .add(wood);
        if(strippedLog != null){
            tag(BlockTags.LOGS)
                    .add(strippedLog)
                    .add(strippedWood);
            tag(BlockTags.LOGS_THAT_BURN)
                    .add(strippedLog)
                    .add(strippedWood);
            tag(BlockTags.MINEABLE_WITH_AXE)
                    .add(strippedLog)
                    .add(strippedWood);
        }
        tag(BlockTags.PLANKS)
                .add(planks);
        tag(BlockTags.STAIRS)
                .add(stairs);
        tag(BlockTags.WOODEN_STAIRS)
                .add(stairs);
        tag(BlockTags.SLABS)
                .add(slab);
        tag(BlockTags.WOODEN_SLABS)
                .add(slab);
        tag(BlockTags.FENCES)
                .add(fence);
        tag(BlockTags.WOODEN_FENCES)
                .add(fence);
        tag(BlockTags.FENCE_GATES)
                .add(fenceGate);
        tag(BlockTags.FENCE_GATES)
                .add(fenceGate);
        tag(BlockTags.BUTTONS)
                .add(button);
        tag(BlockTags.WOODEN_BUTTONS)
                .add(button);
        tag(BlockTags.PRESSURE_PLATES)
                .add(pressurePlate);

        tag(BlockTags.STANDING_SIGNS)
                .add(floorSign);
        tag(BlockTags.WALL_SIGNS)
                .add(wallSign);
        tag(BlockTags.CEILING_HANGING_SIGNS)
                .add(hangingSign);
        tag(BlockTags.WALL_HANGING_SIGNS)
                .add(hangingWallSign);
        tag(BlockTags.ALL_HANGING_SIGNS)
                .add(hangingSign)
                .add(hangingWallSign);
        tag(BlockTags.SIGNS)
                .add(floorSign)
                .add(wallSign);
        tag(BlockTags.ALL_SIGNS)
                .add(floorSign)
                .add(wallSign)
                .add(hangingSign)
                .add(hangingWallSign);

        tag(BlockTags.WOODEN_PRESSURE_PLATES)
                .add(pressurePlate);
        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(log)
                .add(wood)
                .add(planks)
                .add(stairs)
                .add(slab)
                .add(button)
                .add(floorSign)
                .add(wallSign)
                .add(hangingSign)
                .add(hangingWallSign)
                .add(pressurePlate)
                .add(fence)
                .add(fenceGate);
        if (door != null){
            tag(BlockTags.DOORS)
                    .add(door);
            tag(BlockTags.WOODEN_DOORS)
                    .add(door);
            tag(BlockTags.MINEABLE_WITH_AXE)
                    .add(door);
        }
        if (trapdoor != null){
            tag(BlockTags.TRAPDOORS)
                    .add(trapdoor);
            tag(BlockTags.WOODEN_TRAPDOORS)
                    .add(trapdoor);
            tag(BlockTags.MINEABLE_WITH_AXE)
                    .add(trapdoor);
        }
        if (bookshelf != null){
            tag(BlockTags.ENCHANTMENT_POWER_PROVIDER)
                    .add(bookshelf);
            tag(BlockTags.MINEABLE_WITH_AXE)
                    .add(bookshelf);
        }
        if (wainscoting != null){
            tag(BlockTags.MINEABLE_WITH_AXE)
                    .add(wainscoting);
        }
        if (window != null){
            tag(BlockTags.MINEABLE_WITH_AXE)
                    .add(window)
                    .add(pane);
        }
        if (leaves != null){
            tag(BlockTags.LEAVES)
                    .add(leaves);
            tag(BlockTags.MINEABLE_WITH_HOE)
                    .add(leaves);
        }
        if (sapling != null){
            tag(BlockTags.SAPLINGS)
                    .add(sapling);
        }

    }
}
